#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Sibling lockfile: each install_* records the version/checksum it actually
# resolved, giving a reproducible record on top of the always-latest model.
LOCK_FILE="$SCRIPT_DIR/setup_dev_environment.lock"

path_present() {
    [ -e "$1" ] || [ -L "$1" ]
}

# GNU mv -T prevents a directory destination from silently nesting the source;
# -n preserves anything that appears between the caller's check and the move.
# Because -n reports success when it skips, also require the source to vanish.
move_path_exact_noreplace() {
    local source="$1" destination="$2"

    mv -Tn -- "$source" "$destination" || return 1
    ! path_present "$source"
}

# json_patch FILE [JQ_ARGS...] — atomically apply a jq filter to a JSON file,
# seeding with {} if the file does not exist yet.
json_patch() {
    local file="$1"; shift
    local parent
    parent=$(dirname "$file")
    mkdir -p "$parent"
    local input='{}'
    [ -f "$file" ] && input=$(cat "$file")
    local tmp
    tmp=$(mktemp "$parent/.${file##*/}.XXXXXX")
    if printf '%s' "$input" | jq "$@" > "$tmp"; then
        mv -T -- "$tmp" "$file"
    else
        rm -f "$tmp"
        return 1
    fi
}

# Fetch an artifact over HTTPS. Versions are resolved dynamically to the latest
# upstream release, so there is no pre-reviewed digest to check; TLS is the
# transport trust boundary and record_lock captures what each run installed.
download() {
    local url="$1" output="$2"
    curl --proto '=https' --tlsv1.2 -fSL --retry 3 -o "$output" "$url"
}

# Resolve the latest release tag of a GitHub repo without hitting the rate-limited
# API: the /releases/latest page redirects to /releases/tag/<tag>. Echoes the tag
# verbatim (e.g. "v0.11.7" or "0.11.28").
github_latest_tag() {
    local repo="$1" url tag
    url=$(curl --proto '=https' --tlsv1.2 -fsSL -o /dev/null \
        -w '%{url_effective}' "https://github.com/$repo/releases/latest") \
        || return 1
    # Only trust a URL that actually redirected to a specific tag; a repo with no
    # releases stays on /releases/latest and must be treated as a failure.
    case "$url" in
        */releases/tag/*) tag=${url##*/releases/tag/} ;;
        *)
            echo "error: could not resolve latest release tag for $repo" >&2
            return 1
            ;;
    esac
    printf '%s\n' "$tag"
}

# sha256 of a file, bare hex.
sha256_of() { sha256sum "$1" | awk '{print $1}'; }

# record_lock NAME VERSION [DIGEST] — upsert one component's line in the sibling
# lockfile, leaving other components' lines untouched. DIGEST is "algo:hex" or "-"
# when upstream gives us nothing to hash. Lines are kept sorted so selective
# --components runs produce minimal diffs.
record_lock() {
    local name="$1" version="$2" digest="${3:--}" existing="" prior tmp dir
    dir=$(dirname "$LOCK_FILE")
    mkdir -p "$dir" 2>/dev/null || true
    # The lockfile is a convenience record, not required for the install to
    # succeed. If its directory is not writable (e.g. the script lives in a
    # read-only location), warn and carry on instead of aborting the install.
    if [ ! -w "$dir" ]; then
        echo "warn: $dir not writable; skipping lockfile update for $name" >&2
        return 0
    fi
    if [ -f "$LOCK_FILE" ]; then
        # On a no-op run that passes "-", keep the checksum a prior run recorded
        # so the committed lockfile does not churn between "sha256:..." and "-".
        if [ "$digest" = "-" ]; then
            prior=$(awk -F'\t' -v n="$name" '$1 == n {print $3; exit}' "$LOCK_FILE")
            [ -n "$prior" ] && digest="$prior"
        fi
        # Every component line except this one. A single awk (no grep pipe) keeps
        # a zero-match from tripping `set -o pipefail`.
        existing=$(awk -F'\t' -v n="$name" '!/^#/ && NF && $1 != n' "$LOCK_FILE")
    fi
    tmp=$(mktemp "${LOCK_FILE}.XXXXXX") || {
        echo "warn: could not create temp file in $dir; skipping lockfile update for $name" >&2
        return 0
    }
    {
        printf '# Generated by setup_dev_environment.sh; do not edit by hand.\n'
        printf '# component\tversion\tchecksum\n'
        printf '%s\n%s\t%s\t%s\n' "$existing" "$name" "$version" "$digest" \
            | awk 'NF' | LC_ALL=C sort
    } > "$tmp"
    mv -f -- "$tmp" "$LOCK_FILE"
}

# When USE_LOCK=1 (--locked), installers reproduce the versions recorded in the
# lockfile instead of resolving the latest upstream release.
USE_LOCK=0

# lock_version NAME — echo the version recorded for a component in the lockfile.
# Fails (with a message) if the lockfile or the entry is missing.
lock_version() {
    local name="$1" ver
    [ -f "$LOCK_FILE" ] || {
        echo "error: --locked requires $LOCK_FILE, which does not exist" >&2
        return 1
    }
    ver=$(awk -F'\t' -v n="$name" '$1 == n {print $2; exit}' "$LOCK_FILE")
    [ -n "$ver" ] || {
        echo "error: no lockfile entry for '$name' in $LOCK_FILE" >&2
        return 1
    }
    printf '%s\n' "$ver"
}

# resolve_tag COMPONENT REPO — the version/tag an installer should use: the
# recorded value under --locked, otherwise the latest GitHub release tag. Callers
# normalise the leading "v" as they already do, so both paths stay consistent.
resolve_tag() {
    if [ "$USE_LOCK" -eq 1 ]; then
        lock_version "$1"
    else
        github_latest_tag "$2"
    fi
}

# Verify the ordered primary-key fingerprints in an OpenPGP key or keyring.
# A private temporary GNUPGHOME avoids modifying the user's keyring.
verify_openpgp_fingerprints() {
    local key_file="$1" gnupg_home actual expected
    shift
    gnupg_home=$(mktemp -d)
    chmod 700 "$gnupg_home"
    actual=$(
        GNUPGHOME="$gnupg_home" gpg --batch --show-keys --with-colons "$key_file" 2>/dev/null \
            | awk -F: '$1 == "pub" { want = 1; next } want && $1 == "fpr" { print $10; want = 0 }'
    )
    rm -rf "$gnupg_home"
    expected=$(printf '%s\n' "$@")
    if [ "$actual" != "$expected" ]; then
        echo "error: unexpected OpenPGP primary-key fingerprints in $key_file" >&2
        echo "expected:" >&2
        printf '  %s\n' "$@" >&2
        echo "actual:" >&2
        printf '  %s\n' "$actual" >&2
        return 1
    fi
}

activate_staged_tree() {
    local staged="$1" destination="$2" backup="" backup_root=""
    local parent destination_name transfer transfer_root

    parent=$(dirname "$destination")
    destination_name=${destination##*/}
    mkdir -p "$parent"
    transfer_root=$(mktemp -d "$parent/.activate-stage.XXXXXX")
    transfer="$transfer_root/tree"
    if ! move_path_exact_noreplace "$staged" "$transfer"; then
        rm -rf "$transfer_root"
        return 1
    fi

    if path_present "$destination"; then
        backup_root=$(mktemp -d "$parent/.${destination_name}.backup.XXXXXX")
        backup="$backup_root/tree"
        if ! move_path_exact_noreplace "$destination" "$backup"; then
            if path_present "$backup"; then
                echo "error: destination changed while being moved; previous tree remains at $backup" >&2
            else
                echo "error: could not move existing destination aside: $destination" >&2
            fi
            rm -rf "$transfer_root"
            if ! path_present "$backup"; then
                rm -rf "$backup_root"
            fi
            return 1
        fi
    fi
    if ! move_path_exact_noreplace "$transfer" "$destination"; then
        rm -rf "$transfer_root"
        if [ -n "$backup" ]; then
            if path_present "$destination"; then
                echo "error: destination reappeared during activation; previous tree remains at $backup" >&2
            elif ! move_path_exact_noreplace "$backup" "$destination"; then
                echo "error: activation failed and previous tree could not be restored; it remains at $backup" >&2
            else
                rmdir "$backup_root"
            fi
        fi
        return 1
    fi
    rmdir "$transfer_root"
    [ -z "$backup_root" ] || rm -rf "$backup_root"
}

# ---------------------------------------------------------------------------
# Distro detection + package abstraction
# ---------------------------------------------------------------------------

DISTRO=
APT_UPDATED=0

as_root() {
    if [ "$(id -u)" -eq 0 ]; then
        "$@"
    else
        sudo "$@"
    fi
}

detect_distro() {
    if [ -r /etc/os-release ]; then
        # shellcheck disable=SC1091
        . /etc/os-release
    fi
    case "${ID:-}${ID_LIKE:-}" in
        *arch*)            DISTRO=arch ;;
        *debian*|*ubuntu*) DISTRO=debian ;;
        *)
            if   command -v pacman  >/dev/null 2>&1; then DISTRO=arch
            elif command -v apt-get >/dev/null 2>&1; then DISTRO=debian
            else
                echo "Unsupported distro: cannot find pacman or apt-get" >&2
                exit 1
            fi
            ;;
    esac
}

pkg_name() {
    case "$DISTRO:$1" in
        arch:python3-neovim|arch:python3-pynvim) echo python-pynvim ;;
        arch:silversearcher-ag)                   echo the_silver_searcher ;;
        arch:gh)                                  echo github-cli ;;
        arch:usermod)                             echo shadow ;;
        debian:ninja)                             echo ninja-build ;;
        debian:python3-neovim)                    echo python3-pynvim ;;
        debian:usermod)                           echo passwd ;;
        *)                                        echo "$1" ;;
    esac
}

apt_update_once() {
    [ "$APT_UPDATED" -eq 1 ] && return 0
    as_root apt-get update
    APT_UPDATED=1
}

pkg_install() {
    local pkgs=()
    local p
    for p in "$@"; do pkgs+=("$(pkg_name "$p")"); done
    case "$DISTRO" in
        arch)   as_root pacman -S --needed --noconfirm "${pkgs[@]}" ;;
        debian)
            apt_update_once
            as_root env DEBIAN_FRONTEND=noninteractive apt-get install -y "${pkgs[@]}"
            ;;
    esac
}

# ---------------------------------------------------------------------------
# Components: install_<name> and/or config_<name>
# ---------------------------------------------------------------------------

# DEFAULT_COMPONENTS run on a plain (no --components) invocation.
DEFAULT_COMPONENTS=(base chezmoi zsh nvim llvm node claude gh uv precommit hf)
# OPT_IN_COMPONENTS are recognised by --components but excluded from the default
# run. rocq builds a dedicated opam + OCaml + Rocq/Coq toolchain (~10-40 min,
# heavy) needed only for the Software Foundations volumes, so it must be asked
# for explicitly: setup_dev_environment.sh --components rocq
OPT_IN_COMPONENTS=(rocq)
# Full set of valid component names (default + opt-in); used for validation and
# --list-components.
ALL_COMPONENTS=("${DEFAULT_COMPONENTS[@]}" "${OPT_IN_COMPONENTS[@]}")

install_base() {
    # (opam's unzip dependency lives in build_rocq.sh, which is opt-in.)
    pkg_install zsh git curl ca-certificates python3-pynvim silversearcher-ag wget tmux jq ccache gdb sudo usermod cmake ninja fzf
}

# chezmoi manages the dotfiles (and, via ~/.local/share/chezmoi/.chezmoiexternal.toml,
# the Oh My Zsh / tpm / vim-plug trees the dotfiles depend on). Install the pinned
# binary to ~/proot/bin; ~/.env_stow.sh puts that directory on PATH.
install_chezmoi() {
    local tag version platform url tmp digest installed_version=""

    tag=$(resolve_tag chezmoi twpayne/chezmoi) || return 1
    version=${tag#v}

    mkdir -p "$HOME/proot/bin"
    if [ -x "$HOME/proot/bin/chezmoi" ]; then
        installed_version=$("$HOME/proot/bin/chezmoi" --version 2>/dev/null || true)
    fi
    if [[ "$installed_version" == *"version v$version,"* ]]; then
        echo "chezmoi $version already installed; nothing to do."
        record_lock chezmoi "$version" -
        return 0
    fi

    case "$(uname -m)" in
        x86_64|amd64) platform=amd64 ;;
        aarch64|arm64) platform=arm64 ;;
        *)
            echo "error: unsupported chezmoi architecture: $(uname -m)" >&2
            return 1
            ;;
    esac
    url="https://github.com/twpayne/chezmoi/releases/download/v${version}/chezmoi_${version}_linux_${platform}.tar.gz"
    tmp=$(mktemp -d)
    download "$url" "$tmp/chezmoi.tar.gz" || { rm -rf "$tmp"; return 1; }
    digest=$(sha256_of "$tmp/chezmoi.tar.gz")
    tar xzf "$tmp/chezmoi.tar.gz" -C "$tmp" || { rm -rf "$tmp"; return 1; }
    [ -x "$tmp/chezmoi" ] || {
        echo "error: chezmoi archive does not contain the chezmoi binary" >&2
        rm -rf "$tmp"
        return 1
    }
    install -m 0755 "$tmp/chezmoi" "$HOME/proot/bin/chezmoi"
    rm -rf "$tmp"
    [[ "$("$HOME/proot/bin/chezmoi" --version)" == *"version v$version,"* ]] || return 1
    record_lock chezmoi "$version" "sha256:$digest"
}

# Pull in the dotfiles early so later config steps (e.g. config_nvim's PlugUpdate)
# see the applied files and externals. Best-effort: a host without access to the
# private dotfiles repo (e.g. CI with no SSH key) warns and continues.
config_chezmoi() {
    export PATH="$HOME/proot/bin:$PATH"
    local repo="git@github.com:lijinpei-amd/dotfiles.git"
    if [ -d "$HOME/.local/share/chezmoi/.git" ]; then
        chezmoi apply || echo "warn: chezmoi apply failed; continuing" >&2
    else
        chezmoi init --apply "$repo" \
            || echo "warn: chezmoi init failed (no repo access?); continuing" >&2
    fi
}

# ~/.zshrc and ~/.zshenv are managed by chezmoi (they load Oh My Zsh and the
# prompt directly). This step only makes zsh the login shell.
config_zsh() {
    as_root usermod -s "$(command -v zsh)" "$(id -un)"
}

install_nvim() {
    # vim-plug's plug.vim is managed by chezmoi (.chezmoiexternal.toml); this
    # installs only the pinned Neovim binary.
    local tag version platform release_url prefix="$HOME/proot/nvim"
    local tmp staged digest installed_version=""

    tag=$(resolve_tag nvim neovim/neovim) || return 1
    version=${tag#v}

    case "$(uname -m)" in
        x86_64|amd64) platform=x86_64 ;;
        aarch64|arm64) platform=arm64 ;;
        *)
            echo "error: unsupported Neovim architecture: $(uname -m)" >&2
            return 1
            ;;
    esac
    release_url="https://github.com/neovim/neovim/releases/download/v${version}/nvim-linux-${platform}.tar.gz"

    if [ -x "$prefix/bin/nvim" ]; then
        installed_version=$("$prefix/bin/nvim" --version 2>/dev/null | sed -n '1p' || true)
    fi
    if [ "$installed_version" != "NVIM v${version}" ]; then
        tmp=$(mktemp -d)
        staged="$tmp/nvim"
        mkdir "$staged"
        download "$release_url" "$tmp/nvim.tar.gz" || { rm -rf "$tmp"; return 1; }
        digest=$(sha256_of "$tmp/nvim.tar.gz")
        tar xzf "$tmp/nvim.tar.gz" --strip-components=1 -C "$staged" \
            || { rm -rf "$tmp"; return 1; }
        [ "$("$staged/bin/nvim" --version | sed -n '1p')" = "NVIM v${version}" ] || {
            echo "error: downloaded Neovim reports an unexpected version" >&2
            rm -rf "$tmp"
            return 1
        }
        activate_staged_tree "$staged" "$prefix" || { rm -rf "$tmp"; return 1; }
        rm -rf "$tmp"
        record_lock nvim "$version" "sha256:$digest"
    else
        record_lock nvim "$version" -
    fi
    export PATH="$prefix/bin:$PATH"
}

config_nvim() {
    local init_lua="$HOME/.config/nvim/init.lua"
    local plug_vim="${XDG_DATA_HOME:-$HOME/.local/share}/nvim/site/autoload/plug.vim"
    if [ ! -f "$init_lua" ]; then
        echo "    (skipping PlugUpdate: $init_lua is not installed; run chezmoi apply first)" >&2
    elif [ -f "$plug_vim" ] && command -v nvim >/dev/null 2>&1; then
        # plug.vim itself is installed from a verified commit in install_nvim;
        # keep that reviewed manager revision unchanged.
        # PlugUpdate also forces existing plugin checkouts to their declared
        # commits; PlugInstall would leave already-present mutable HEADs alone.
        nvim -c 'PlugUpdate --sync' -c qall
    else
        echo "    (skipping PlugUpdate: vim-plug or nvim not installed)" >&2
    fi
}

install_llvm() {
    local v=""
    case "$DISTRO" in
        # pacman installs the current repo version; --locked cannot pin it here.
        arch)   pkg_install llvm clang lld ;;
        debian)
            # Pull llvm.sh from the repo's default branch and run it without a
            # version argument: it installs the current stable LLVM (latest).
            local installer_url="https://raw.githubusercontent.com/opencollab/llvm-jenkins.debian.net/HEAD/llvm.sh"
            local llvm_key_url="https://apt.llvm.org/llvm-snapshot.gpg.key"
            local llvm_key_fingerprint="6084F3CF814B57C1CF12EFD515CF4D18AF4F7421"  # pragma: allowlist secret  gitleaks:allow
            local tmpdir

            pkg_install gnupg lsb-release software-properties-common
            tmpdir=$(mktemp -d)
            download "$llvm_key_url" "$tmpdir/llvm-snapshot.gpg.key" \
                || { rm -rf "$tmpdir"; return 1; }
            # Identity check on the signing key (version-agnostic) is retained.
            verify_openpgp_fingerprints "$tmpdir/llvm-snapshot.gpg.key" "$llvm_key_fingerprint" \
                || { rm -rf "$tmpdir"; return 1; }
            as_root install -m 0644 "$tmpdir/llvm-snapshot.gpg.key" \
                /etc/apt/trusted.gpg.d/apt.llvm.org.asc \
                || { rm -rf "$tmpdir"; return 1; }

            download "$installer_url" "$tmpdir/llvm.sh" \
                || { rm -rf "$tmpdir"; return 1; }
            # Under --locked, install the recorded major version; otherwise pass
            # no version so llvm.sh picks the current stable (latest).
            local locked_v="" llvm_args=()
            if [ "$USE_LOCK" -eq 1 ]; then
                locked_v=$(lock_version llvm) || { rm -rf "$tmpdir"; return 1; }
                llvm_args=("$locked_v")
            fi
            if ! as_root bash "$tmpdir/llvm.sh" "${llvm_args[@]}"; then
                rm -rf "$tmpdir"
                return 1
            fi
            rm -rf "$tmpdir"

            if [ -n "$locked_v" ]; then
                v="$locked_v"
            else
                # Detect the LLVM major version llvm.sh just installed (highest
                # /usr/bin/clang-N) to drive the update-alternatives wiring.
                local clang_bin n
                for clang_bin in /usr/bin/clang-[0-9]*; do
                    [ -e "$clang_bin" ] || continue
                    n="${clang_bin##*/clang-}"
                    case "$n" in *[!0-9]*) continue ;; esac
                    if [ -z "$v" ] || [ "$n" -gt "$v" ]; then v="$n"; fi
                done
            fi
            [ -n "$v" ] || { echo "error: could not detect installed clang version" >&2; return 1; }
            as_root update-alternatives --install /usr/bin/clang   clang   "/usr/bin/clang-$v"   100
            as_root update-alternatives --install /usr/bin/clang++ clang++ "/usr/bin/clang++-$v" 100
            as_root update-alternatives --set clang   "/usr/bin/clang-$v"
            as_root update-alternatives --set clang++ "/usr/bin/clang++-$v"
            # llvm.sh installs lld-$v but only as versioned binaries; clang's
            # -fuse-ld=lld (set by our LLVM_ENABLE_LLD=ON build) searches PATH
            # for an unversioned ld.lld, so wire that up too or linking fails
            # with "invalid linker name in argument '-fuse-ld=lld'".
            as_root update-alternatives --install /usr/bin/ld.lld ld.lld "/usr/bin/ld.lld-$v" 100
            as_root update-alternatives --install /usr/bin/lld    lld    "/usr/bin/lld-$v"    100
            as_root update-alternatives --set ld.lld "/usr/bin/ld.lld-$v"
            as_root update-alternatives --set lld    "/usr/bin/lld-$v"
            ;;
    esac
    if [ -z "$v" ]; then
        v=$(clang --version 2>/dev/null \
            | sed -n 's/.*clang version \([0-9]\+\).*/\1/p' | head -1) || true
    fi
    record_lock llvm "${v:-unknown}" -
}

# Rocq prover (formerly Coq), for the Software Foundations volumes. build_rocq.sh
# compiles Rocq 9.0.x + coq-simple-io into its own opam root at ~/proot/rocq and
# is idempotent (no-op if already built). The env vars (OPAMROOT, switch PATH,
# OCaml runtime paths) are managed separately by chezmoi in ~/.env_stow.sh.
install_rocq() { "$SCRIPT_DIR/build_rocq.sh"; }

install_node() {
    local nvm_tag nvm_url tmp node_version digest
    local cc_version cc_integ cx_version cx_integ

    export NVM_DIR="$HOME/.nvm"

    # Install/refresh nvm's own source tree at the latest release tag. The marker
    # records the installed tag so the source is only re-fetched when it changes;
    # installed Node versions and aliases under $NVM_DIR are preserved.
    nvm_tag=$(resolve_tag nvm nvm-sh/nvm) || return 1
    nvm_url="https://codeload.github.com/nvm-sh/nvm/tar.gz/${nvm_tag}"
    if [ ! -f "$NVM_DIR/.nvm-installed-tag" ] \
        || [ "$(cat "$NVM_DIR/.nvm-installed-tag")" != "$nvm_tag" ] \
        || [ ! -s "$NVM_DIR/nvm.sh" ]; then
        tmp=$(mktemp -d)
        mkdir "$tmp/staged"
        download "$nvm_url" "$tmp/nvm.tar.gz" || { rm -rf "$tmp"; return 1; }
        digest=$(sha256_of "$tmp/nvm.tar.gz")
        tar xzf "$tmp/nvm.tar.gz" --strip-components=1 -C "$tmp/staged" \
            || { rm -rf "$tmp"; return 1; }
        [ -s "$tmp/staged/nvm.sh" ] || {
            echo "error: nvm archive lacks nvm.sh" >&2
            rm -rf "$tmp"
            return 1
        }
        mkdir -p "$NVM_DIR"
        cp -a "$tmp/staged/." "$NVM_DIR/"
        printf '%s\n' "$nvm_tag" > "$NVM_DIR/.nvm-installed-tag"
        rm -rf "$tmp"
        record_lock nvm "$nvm_tag" "sha256:$digest"
    else
        record_lock nvm "$nvm_tag" -
    fi

    # shellcheck disable=SC1091
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    # Install Node.js and make it the default: the locked version under --locked,
    # otherwise the latest LTS ("lts/*" is resolved by nvm at runtime). The
    # default alias is written directly rather than via `nvm alias`: nvm install
    # is || -guarded (so errexit is suppressed inside it), but a bare `nvm alias`
    # would run with errexit active and could abort on a benign internal status.
    mkdir -p "$NVM_DIR/alias"
    if [ "$USE_LOCK" -eq 1 ]; then
        node_version=$(lock_version node) || return 1
        nvm install "$node_version" || return 1
        printf '%s\n' "$node_version" > "$NVM_DIR/alias/default"
        nvm use --silent "$node_version"
    else
        nvm install --lts || return 1
        printf 'lts/*\n' > "$NVM_DIR/alias/default"
        nvm use --lts --silent
    fi
    node_version=$(node --version)
    record_lock node "$node_version" -

    # Install the Claude Code and Codex CLIs. npm runs its own postinstall (which
    # fetches each tool's native binary); this replaces the former offline
    # pinned-tarball dance. Versions come from the lockfile under --locked.
    local cc_spec cx_spec
    if [ "$USE_LOCK" -eq 1 ]; then
        cc_version=$(lock_version claude-code) || return 1
        cx_version=$(lock_version codex) || return 1
        cc_spec="@anthropic-ai/claude-code@${cc_version}"
        cx_spec="@openai/codex@${cx_version}"
    else
        cc_spec="@anthropic-ai/claude-code@latest"
        cx_spec="@openai/codex@latest"
    fi
    npm install -g --no-audit --no-fund "$cc_spec" "$cx_spec" || return 1
    claude --version >/dev/null
    codex --version >/dev/null

    # Record resolved versions + registry integrity (sha512) for the lockfile.
    # Note: in the @latest case this re-queries the registry, so a publish in the
    # seconds between install and query could record a version newer than the one
    # just installed. Cosmetic only; the installed binaries are the source of truth.
    cc_version=$(npm view "$cc_spec" version 2>/dev/null || echo "")
    cc_integ=$(npm view "$cc_spec" dist.integrity 2>/dev/null || echo "")
    cx_version=$(npm view "$cx_spec" version 2>/dev/null || echo "")
    cx_integ=$(npm view "$cx_spec" dist.integrity 2>/dev/null || echo "")
    record_lock claude-code "${cc_version:-unknown}" "${cc_integ:+${cc_integ/-/:}}"
    record_lock codex "${cx_version:-unknown}" "${cx_integ:+${cx_integ/-/:}}"
}

config_claude() {
    json_patch ~/.claude.json '.hasCompletedOnboarding = true'
    # Durable Claude Code configuration is managed separately by chezmoi at
    # git@github.com:lijinpei-amd/dotfiles.git. Gateway settings and credentials
    # remain out-of-band (for example, exported from the personal ~/.env.sh).
}

install_gh() {
    case "$DISTRO" in
        # pacman installs the current repo version; --locked cannot pin it here.
        arch)
            pkg_install gh
            ;;
        debian)
            local keyring=/etc/apt/keyrings/githubcli-archive-keyring.gpg
            local sources=/etc/apt/sources.list.d/github-cli.list
            local key_url="https://cli.github.com/packages/githubcli-archive-keyring.gpg"
            local tmpdir
            pkg_install gnupg
            tmpdir=$(mktemp -d)
            as_root mkdir -p -m 755 /etc/apt/keyrings /etc/apt/sources.list.d
            download "$key_url" "$tmpdir/github-cli.gpg" \
                || { rm -rf "$tmpdir"; return 1; }
            # Identity check on the signing key (version-agnostic) is retained.
            verify_openpgp_fingerprints "$tmpdir/github-cli.gpg" \
                2C6106201985B60E6C7AC87323F3D4EA75716059 \
                7F38BBB59D064DBCB3D84D725612B36462313325 \
                || { rm -rf "$tmpdir"; return 1; }
            as_root install -m 0644 "$tmpdir/github-cli.gpg" "$keyring" \
                || { rm -rf "$tmpdir"; return 1; }
            rm -rf "$tmpdir"
            echo "deb [arch=$(dpkg --print-architecture) signed-by=$keyring] https://cli.github.com/packages stable main" \
                | as_root tee "$sources" >/dev/null
            as_root apt-get update
            local gh_pkg=gh
            if [ "$USE_LOCK" -eq 1 ]; then
                local gh_ver
                gh_ver=$(lock_version gh) || return 1
                # Best-effort pin: the recorded version comes from `gh --version`
                # and the apt package version may not match it exactly (suffix or
                # different formatting), and old builds age out of the repo. If the
                # exact version is not available, fall back to latest with a warning
                # rather than fail; gh is not reproducibly pinnable through apt.
                if apt-cache show "gh=${gh_ver}" >/dev/null 2>&1; then
                    gh_pkg="gh=${gh_ver}"
                else
                    echo "warn: gh $gh_ver no longer in apt repo; installing latest" >&2
                fi
            fi
            as_root env DEBIAN_FRONTEND=noninteractive apt-get install -y "$gh_pkg"
            ;;
    esac
    record_lock gh "$(gh --version 2>/dev/null | sed -n 's/^gh version \([0-9.]*\).*/\1/p' | head -1)" -
}

install_uv() {
    local version platform url tmp source_dir digest installed_version=""

    version=$(resolve_tag uv astral-sh/uv) || return 1
    version=${version#v}

    mkdir -p "$HOME/.local/bin"
    if [ -x "$HOME/.local/bin/uv" ]; then
        installed_version=$("$HOME/.local/bin/uv" --version 2>/dev/null || true)
    fi
    if [ -x "$HOME/.local/bin/uv" ] && [ -x "$HOME/.local/bin/uvx" ] \
        && [[ "$installed_version" == "uv $version"* ]]; then
        echo "uv $version already installed; nothing to do."
        record_lock uv "$version" -
        return 0
    fi

    case "$(uname -m)" in
        x86_64|amd64) platform=x86_64-unknown-linux-gnu ;;
        aarch64|arm64) platform=aarch64-unknown-linux-gnu ;;
        *)
            echo "error: unsupported uv architecture: $(uname -m)" >&2
            return 1
            ;;
    esac
    url="https://github.com/astral-sh/uv/releases/download/${version}/uv-${platform}.tar.gz"
    tmp=$(mktemp -d)
    download "$url" "$tmp/uv.tar.gz" || { rm -rf "$tmp"; return 1; }
    digest=$(sha256_of "$tmp/uv.tar.gz")
    tar xzf "$tmp/uv.tar.gz" -C "$tmp" || { rm -rf "$tmp"; return 1; }
    source_dir="$tmp/uv-${platform}"
    install -m 0755 "$source_dir/uv" "$HOME/.local/bin/uv"
    install -m 0755 "$source_dir/uvx" "$HOME/.local/bin/uvx"
    rm -rf "$tmp"
    [[ "$("$HOME/.local/bin/uv" --version)" == "uv $version"* ]] || return 1
    record_lock uv "$version" "sha256:$digest"
}

ensure_uv() {
    export PATH="$HOME/.local/bin:$PATH"
    install_uv
    export PATH="$HOME/.local/bin:$PATH"
}

# Install a uv tool (latest PyPI release, or the locked version under --locked)
# and record it in the lockfile. uv normalises names with dashes in
# `uv tool list` (e.g. huggingface-hub).
install_uv_tool() {
    local pkg="$1" listed ver spec
    listed=${pkg//_/-}
    if [ "$USE_LOCK" -eq 1 ]; then
        ver=$(lock_version "$listed") || return 1
        spec="${pkg}==${ver}"
    else
        spec="$pkg"
    fi
    uv tool install --force "$spec" || return 1
    ver=$(uv tool list 2>/dev/null | awk -v t="$listed" '$1==t {print $2; exit}')
    record_lock "$listed" "${ver:-unknown}" -
}

# Download a .tar.gz, extract a single named binary into ~/.local/bin, and leave
# the archive's sha256 in TAR_BINARY_DIGEST for the caller to record.
TAR_BINARY_DIGEST=""
install_tar_binary() {
    local name="$1" url="$2"
    local tmp
    tmp=$(mktemp -d)
    download "$url" "$tmp/archive.tar.gz" || { rm -rf "$tmp"; return 1; }
    TAR_BINARY_DIGEST=$(sha256_of "$tmp/archive.tar.gz")
    tar -xzf "$tmp/archive.tar.gz" -C "$tmp" || { rm -rf "$tmp"; return 1; }
    [ -x "$tmp/$name" ] || {
        echo "error: archive does not contain $name" >&2
        rm -rf "$tmp"
        return 1
    }
    mkdir -p "$HOME/.local/bin"
    install -m 0755 "$tmp/$name" "$HOME/.local/bin/$name"
    rm -rf "$tmp"
}

install_precommit() {
    ensure_uv
    install_uv_tool pre-commit
    install_uv_tool detect-secrets

    local os arch gitleaks_platform trufflehog_platform
    os=$(uname -s)
    arch=$(uname -m)
    if [ "$os" != Linux ]; then
        echo "error: precommit binary install currently supports Linux only, got $os" >&2
        return 1
    fi
    case "$arch" in
        x86_64|amd64)
            gitleaks_platform=linux_x64
            trufflehog_platform=linux_amd64
            ;;
        aarch64|arm64)
            gitleaks_platform=linux_arm64
            trufflehog_platform=linux_arm64
            ;;
        *)
            echo "error: unsupported architecture for precommit tools: $arch" >&2
            return 1
            ;;
    esac

    local gitleaks_tag gitleaks_version trufflehog_tag trufflehog_version
    gitleaks_tag=$(resolve_tag gitleaks gitleaks/gitleaks) || return 1
    gitleaks_version=${gitleaks_tag#v}
    gitleaks_tag="v${gitleaks_version}"
    install_tar_binary \
        gitleaks \
        "https://github.com/gitleaks/gitleaks/releases/download/${gitleaks_tag}/gitleaks_${gitleaks_version}_${gitleaks_platform}.tar.gz" \
        || return 1
    record_lock gitleaks "$gitleaks_version" "sha256:$TAR_BINARY_DIGEST"

    trufflehog_tag=$(resolve_tag trufflehog trufflesecurity/trufflehog) || return 1
    trufflehog_version=${trufflehog_tag#v}
    trufflehog_tag="v${trufflehog_version}"
    install_tar_binary \
        trufflehog \
        "https://github.com/trufflesecurity/trufflehog/releases/download/${trufflehog_tag}/trufflehog_${trufflehog_version}_${trufflehog_platform}.tar.gz" \
        || return 1
    record_lock trufflehog "$trufflehog_version" "sha256:$TAR_BINARY_DIGEST"
}

config_precommit() {
    export PATH="$HOME/.local/bin:$PATH"
    if [ -f "$SCRIPT_DIR/.pre-commit-config.yaml" ] && command -v pre-commit >/dev/null 2>&1; then
        (cd "$SCRIPT_DIR" && pre-commit install)
    else
        echo "    (skipping pre-commit install: config or pre-commit not found)" >&2
    fi
}

install_hf() {
    ensure_uv
    install_uv_tool huggingface_hub
}

# ---------------------------------------------------------------------------
# Driver: arg parsing, validation, dispatch
# ---------------------------------------------------------------------------

DO_INSTALL=1
DO_CONFIG=1
COMPONENTS=()

has_fn() { declare -F "$1" >/dev/null; }

usage() {
    cat <<EOF
Usage: $(basename "$0") [OPTIONS]

  --config-only          Skip install steps; run only config steps.
  --install-only         Skip config steps; run only install steps.
  --locked               Install the versions recorded in the lockfile
                         ($(basename "$LOCK_FILE")) instead of the latest release.
                         Applies to source/tarball/npm/uv components; distro
                         packages installed via pacman (Arch: llvm, gh) always
                         track the repo and cannot be pinned.
  --components LIST      Comma-separated component names to act on.
                         Default: all default components (opt-in ones excluded).
  --list-components      Print available components and exit.
  -h, --help             Show this help.

--config-only and --install-only are mutually exclusive.
--components is independent: it narrows which components run, in either mode.

Default components:
  ${DEFAULT_COMPONENTS[*]}
Opt-in components (run only when named with --components):
  ${OPT_IN_COMPONENTS[*]}
EOF
}

list_components() {
    local c optin
    declare -A optin=()
    for c in "${OPT_IN_COMPONENTS[@]}"; do optin[$c]=1; done
    for c in "${ALL_COMPONENTS[@]}"; do
        local has_install=no has_config=no tag=""
        has_fn "install_$c" && has_install=yes
        has_fn  "config_$c" && has_config=yes
        [ -n "${optin[$c]:-}" ] && tag="  (opt-in)"
        printf '  %-10s  install=%-3s  config=%-3s%s\n' "$c" "$has_install" "$has_config" "$tag"
    done
}

parse_args() {
    while [ $# -gt 0 ]; do
        case "$1" in
            --config-only)   DO_INSTALL=0; shift ;;
            --install-only)  DO_CONFIG=0;  shift ;;
            --locked)        USE_LOCK=1;   shift ;;
            --components)
                [ $# -ge 2 ] || { echo "error: --components needs an argument" >&2; exit 2; }
                IFS=, read -r -a COMPONENTS <<< "$2"
                shift 2
                ;;
            --components=*)
                IFS=, read -r -a COMPONENTS <<< "${1#--components=}"
                shift
                ;;
            --list-components) list_components; exit 0 ;;
            -h|--help)         usage; exit 0 ;;
            --) shift; break ;;
            *)
                echo "error: unknown option: $1" >&2
                usage >&2
                exit 2
                ;;
        esac
    done
    if [ "$DO_INSTALL" -eq 0 ] && [ "$DO_CONFIG" -eq 0 ]; then
        echo "error: --config-only and --install-only are mutually exclusive" >&2
        exit 2
    fi
}

validate_components() {
    local known c
    declare -A known=()
    for c in "${ALL_COMPONENTS[@]}"; do known[$c]=1; done
    for c in "$@"; do
        if [ -z "${known[$c]:-}" ]; then
            echo "error: unknown component: $c" >&2
            echo "known components: ${ALL_COMPONENTS[*]}" >&2
            exit 2
        fi
    done
}

run_component() {
    local name="$1"
    if [ "$DO_INSTALL" -eq 1 ] && has_fn "install_$name"; then
        echo "==> install: $name"
        "install_$name"
    fi
    if [ "$DO_CONFIG" -eq 1 ] && has_fn "config_$name"; then
        echo "==> config:  $name"
        "config_$name"
    fi
}

main() {
    parse_args "$@"
    detect_distro
    local mode_label
    if   [ "$DO_INSTALL" -eq 0 ]; then mode_label=config-only
    elif [ "$DO_CONFIG"  -eq 0 ]; then mode_label=install-only
    else mode_label=full; fi
    echo "==> distro: $DISTRO   mode: $mode_label"

    local selected
    if [ "${#COMPONENTS[@]}" -eq 0 ]; then
        # Opt-in components (e.g. rocq) are deliberately excluded here; request
        # them explicitly with --components.
        selected=("${DEFAULT_COMPONENTS[@]}")
    else
        selected=("${COMPONENTS[@]}")
    fi
    validate_components "${selected[@]}"

    local c
    for c in "${selected[@]}"; do run_component "$c"; done
}

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
    main "$@"
fi
